### ISSUE TITLE
Can't resolve 'react-router-dom'

### ISSUE THREAD

**Issue by lukasoppermann** [antonioru/beautiful-react-hooks#366]
Hey,

I am getting the following error with Next.js@12, react@18 and beautiful-react-hooks@3.2.3

`Header.tsx` has the following import statement:

```js
import { useWindowScroll, useThrottledCallback } from 'beautiful-react-hooks'; 
```

Please let me know what other info I can provide. I don't know what I am doing wrong here.

```
error - ./node_modules/beautiful-react-hooks/esm/useQueryParam.js:1:0
Module not found: Can't resolve 'react-router-dom'

Import trace for requested module:
./node_modules/beautiful-react-hooks/esm/index.js
./components/Header/Header.tsx
./pages/_app.tsx
```

**Comment by antonioru** [comment]
> Hey,
> 
> I am getting the following error with Next.js@12, react@18 and beautiful-react-hooks@3.2.3
> 
> `Header.tsx` has the following import statement:
> 
> ```js
> import { useWindowScroll, useThrottledCallback } from 'beautiful-react-hooks'; 
> ```
> 
> Please let me know what other info I can provide. I don't know what I am doing wrong here.
> 
> ```
> error - ./node_modules/beautiful-react-hooks/esm/useQueryParam.js:1:0
> Module not found: Can't resolve 'react-router-dom'
> 
> Import trace for requested module:
> ./node_modules/beautiful-react-hooks/esm/index.js
> ./components/Header/Header.tsx
> ./pages/_app.tsx
> ```

Hi @lukasoppermann, thanks for opening this issue but looks like you're importing the entire library from `index.ts` and therefore importing `useQueryParam` which relies on `react-router-dom`. 

You should import only hooks that you're using, follow the documentation examples

**Comment by lukasoppermann** [comment]
Did this change "recently"? Anyway, that of course helped. Thank you very much.

**Comment by antonioru** [comment]
> Did this change "recently"? Anyway, that of course helped. Thank you very much.

mh, yes and no... the `index.ts` is there since the first releases but I've recently introduced hooks that are in fact relying on third parties, hence the issue. I had to fix the documentation to encourage importing single imports, that's correct 

I will probably be deprecating the index file soon as it causes more troubles than anything

**Comment by antonioru** [comment]
> Did this change "recently"? Anyway, that of course helped. Thank you very much.

mh, yes and no... the `index.ts` is there since the first releases but I've recently introduced hooks that are in fact relying on third parties, hence the issue. I had to fix the documentation to encourage importing single imports, that's correct 

I will probably be deprecating the index file soon as it causes more troubles than anything

**Comment by wouterds** [comment]
This causes issues for people using this lib on platforms like react-native. While it's true it can be fixed by importing each hook separately from their own file it is an inconvenient breaking change and required us to fix quite a few components.

**Comment by robinclaes** [comment]
+1, not usable on React native at the moment.

**Comment by wouterds** [comment]
Don't think they'll be rolling back, possible to use by changing your imports, but still, annoying breaking change.

```diff
-import { usePreviousValue } from 'beautiful-react-hooks'
+import usePreviousValue from 'beautiful-react-hooks/usePreviousValue'
```
