### ISSUE TITLE
Update `react-router-dom` to v6

### ISSUE THREAD

**Issue by carlosrsabreu** [antonioru/beautiful-react-hooks#389]
**Is your feature request related to a problem? Please describe.**

At this moment, the `react-router-dom` dependency is at v5.  Sometimes, I get an error on vercel deployment because of the `useHistory` hook import, despite it shouldn't be a problem in v5:

```
../../node_modules/beautiful-react-hooks/esm/useQueryParam.js
Attempted import error: 'useHistory' is not exported from 'react-router-dom' (imported as 'useHistory').
```

**Describe the solution you'd like**
It would be nice to update the `react-router-dom` dependency to v6, changing the `useHistory` hook to `useNavigate`: https://github.com/remix-run/react-router/blob/main/docs/getting-started/tutorial.md

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by antonioru** [comment]
@carlosrsabreu hi Carlos, thanks for opening this issue... 

`useQueryParam` is build to provide a state-like functionality to change the URL query parameters in react-router-dom version 5. 
In react-router 6 this can easily be archived by simply using `useSearchParams` from `react-router-dom`, please read the documentation [here](https://reactrouter.com/docs/en/v6/hooks/use-search-params)

For this reason is pointless to update `react-router-dom` to version 6

**Comment by cymen** [comment]
If you're using vite and you run into this issue like so:

```
'useHistory' is not exported by ../node_modules/react-router-dom/index.js, imported by node_modules/beautiful-react-hooks/esm/useQueryParam.js
file: /Users/cymen/dev/surge/gondor/component-library/node_modules/beautiful-react-hooks/esm/useQueryParam.js:2:9
1: import { useCallback, useRef } from 'react';
2: import { useHistory } from 'react-router-dom';
            ^
3: import useDidMount from './useDidMount';
4: import useURLSearchParams from './useURLSearchParams';
```

The solution is to do as the README examples show and import the hooks like so:

```js
import useGlobalEvent from "beautiful-react-hooks/useGlobalEvent";
```

Instead of:

```js
import { useGlobalEvent } from "beautiful-react-hooks";
```

**Comment by BenjaminVanRyseghem** [comment]
Using @cymen workaround works, yet my IDE complains, so it's a bit annoying 😕
